[[redirects]]
from = "/2023/08/3-trucs-a-faire-en-aout-au-jardin/"
to = "https://hugo.jeremielitzler.fr/post/2023/3-trucs-a-faire-en-aout-au-jardin/"
status = 301
force = true


#[[headers]]
#for = "/*"
#[headers.values]
#Content-Security-Policy = "default-src 'self';"

# Thanks to https://answers.netlify.com/t/support-guide-how-to-use-the-ignore-command/37517
[build]
ignore = "exit 1"
